[repository]
name = "hyprland-plugins"
authors = ["tijsb"]
commit_pins = [
    # Hyprland v0.45.0
    ["d2a1e19839ff76d920bacce2153d0bf78559af11", "a425fbebe4cf4238e48a42f724ef2208959d66c"]
]


[synced-monitors]
description = "Sync workspaces across monitors"
authors = ["tijsb"]
output = "synced-monitors/sync-monitors.so"
build = [
    "make -C synced-monitors all"
]
